Adjust serp new

diff --git a/serp-new b/serp-new
--- a/serp-new
+++ b/serp-new
@@ -33,14 +33,15 @@ set -e
 #~
 #~ OPTIONS
 #~
+#~ Modules:
 #~   --with-docling         - Add Docling library (adds ~800MB to the project)
 #~   --with-ai              - Add AI libraries OpenAI, Anthropic, Google
 #~                            Generative AI, LangChain, HuggingFace
 #~   --with-geoip           - Add GeoIP to get users location
 #~
-#~ COMMANDS
-#~
-#~   --help            - View these usage instructions
+#~ Commands:
+#~   --quiet                - Suppress output
+#~   --help                 - View these usage instructions
 #~
 
 log() {
@@ -75,6 +76,29 @@ function validate_project_name() {
 ############################################################
 # Main Script
 ############################################################
+
+makequiet() {
+    if [ "$1" != "true" ] && [ "$1" != "false" ]; then
+        echo "Error: First argument must be 'true' or 'false'"
+        return 1
+    fi
+    
+    local should_quiet="$1"
+    shift  # Remove the quiet boolean from arguments
+    
+    if [ "$should_quiet" == "true" ]; then
+        "$@" > /dev/null
+    else
+        "$@"
+    fi
+}
+
+post_install_message() {
+  GREEN="\033[32m"
+  RED="\033[31m"
+  RESET="\033[0m"
+  echo -e "Activate ${RED}venv${RESET} to use the project with ${GREEN}\`source venv/bin/activate\`.${RESET}"
+}
 
 # Libraries.
 function add_docling() {
@@ -153,6 +177,9 @@ function new_app() {
     exit 1
   fi
 
+  # Get project parameters
+  quiet=$([[ " ${params[@]} " =~ " --quiet " || " ${params[@]} " =~ " --silent " ]] && echo "true" || echo "false")
+
   # Store project name
   local project_name="$1"
   shift
@@ -175,6 +202,7 @@ function new_app() {
   # Copy files
   rsync -a \
     --exclude 'venv/' \
+    --exclude '.venv/' \
     --exclude '.git/' \
     --exclude '**/__pycache__/' \
     --exclude '**/*.pyc' \
@@ -185,14 +213,12 @@ function new_app() {
     --exclude '**/.DS_Store' \
     "$TEMPLATE_DIR/" .
 
-  tree -a -I venv -I .git
-
   # Install dependencies from pyproject.toml and poetry.lock
-  poetry install --no-root
-  poetry env activate
+  makequiet $quiet poetry install --no-root
+  makequiet $quiet poetry env activate
 
   # Install optional libraries.
-  install_optional_libraries "${params[@]}"
+  makequiet $quiet install_optional_libraries "${params[@]}"
 
   # Update env, config, core settings
   apply_env $project_name
@@ -200,15 +226,18 @@ function new_app() {
 
   # Use alembic for migrations (alembic init db/migrations)
   # Setup the database with dbcreate and dbload
-  serp dbcreate
-  serp dbload
+  makequiet $quiet serp dbcreate
+  makequiet $quiet serp dbload
 
   # Persist to repository
   git add .
   git commit -m "Initial commit" > /dev/null
 
   # Output project structure
-  tree -a -I venv -I .git
+  makequiet $quiet tree -a -I venv -I .git
+
+  # Post install message
+  makequiet $quiet post_install_message
 }
 
 ############################################################
